### ISSUE TITLE
Test Annotations/Complex-08 appears to be incorrect

### ISSUE THREAD

**Issue by kdubb** [raml-org/raml-tck#141]
In `lib.raml` the `bindingDefinition` annotation type is defined as follows (notice the lack of `additionalProperties: false`):
```
annotationTypes:
  bindingDefinition:
    displayName: BindingDefinition
    type: array
    items:
      properties:
        method:
          type: string
          required: true
          description: This field defines to which method the binding applies
          enum: ["GET", "PATCH", "POST", "PUT", "DELETE"]
        input:
          type: string
          required: true
          description: The binding related to the field when used as an input
          enum: ["OPTIONAL", "REQUIRED", "NONE"]
        output:
          type: string
          required: true
          description: The binding related to the field when used as an output
          enum: ["OPTIONAL", "REQUIRED", "NONE"]
```

The "invalid" test tries to make it invalid by adding an extra property `hi`. Without the `additionalProperties: false` in the definition this seems to be a valid test even though it expects it to be invalid.
