### ISSUE TITLE
repeat is false for array types

### ISSUE THREAD

**Issue by xaka** [raml-org/raml-tck#33]
RAML 1.0:

```
types:
  Person:
    properties:
      addresses: string[]
```

JSON:

```
          "addresses": {
            "displayName": "addresses",
            "name": "addresses",
            "type": [
              "string[]"
            ],
            "repeat": false,
            "required": true
          }
```

I was expecting `repeat` to be `true` for array types.
