### ISSUE TITLE
Fix TCK/RAML10/Examples/test045/api.raml

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-tck#52]
Example must be specified as

```
        examples:
          one_dept:
            strict: true
            value:
              - X-Dept: 230-OCTO
```

, and the parser must report incorrect type: "string is expected"
